In [2]:
import tensorflow as tf
import numpy as np

In [3]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

In [6]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [7]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [8]:
# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                  feed_dict={x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  16351.558 
Prediction:
 [31.795729 52.203884 44.003063 52.313686 39.36964 ]
10 Cost:  14.054588 
Prediction:
 [144.87825 188.098   177.91373 198.13658 143.01904]
20 Cost:  13.855043 
Prediction:
 [145.23239 188.50107 178.3227  198.5795  143.32289]
30 Cost:  13.805342 
Prediction:
 [145.24539 188.49417 178.3277  198.58252 143.31406]
40 Cost:  13.7558775 
Prediction:
 [145.25739 188.48613 178.33154 198.58424 143.30437]
50 Cost:  13.706721 
Prediction:
 [145.26929 188.47804 178.33531 198.58592 143.29466]
60 Cost:  13.657753 
Prediction:
 [145.28119 188.47    178.3391  198.5876  143.28497]
70 Cost:  13.609085 
Prediction:
 [145.29305 188.46196 178.34285 198.58928 143.27534]
80 Cost:  13.560641 
Prediction:
 [145.30487 188.45395 178.34662 198.59094 143.26572]
90 Cost:  13.512464 
Prediction:
 [145.3167  188.446   178.35039 198.59264 143.25613]
100 Cost:  13.464482 
Prediction:
 [145.32845 188.43799 178.3541  198.59425 143.24654]
110 Cost:  13.416806 
Prediction:
 [145.3402  188.430

990 Cost:  10.049443 
Prediction:
 [146.26244 187.8071  178.6522  198.71745 142.49666]
1000 Cost:  10.019236 
Prediction:
 [146.27174 187.80081 178.65518 198.7186  142.48929]
1010 Cost:  9.989147 
Prediction:
 [146.28102 187.79454 178.65814 198.7197  142.4819 ]
1020 Cost:  9.959181 
Prediction:
 [146.2903  187.78828 178.66113 198.72083 142.47458]
1030 Cost:  9.929378 
Prediction:
 [146.29955 187.78206 178.6641  198.72192 142.46727]
1040 Cost:  9.89976 
Prediction:
 [146.30876 187.77583 178.66705 198.72305 142.45999]
1050 Cost:  9.870267 
Prediction:
 [146.31798 187.76965 178.67001 198.72418 142.45271]
1060 Cost:  9.84094 
Prediction:
 [146.32712 187.76344 178.67294 198.72525 142.44545]
1070 Cost:  9.811725 
Prediction:
 [146.33629 187.75728 178.67587 198.72636 142.43822]
1080 Cost:  9.782655 
Prediction:
 [146.34541 187.75111 178.6788  198.72745 142.431  ]
1090 Cost:  9.753767 
Prediction:
 [146.35452 187.745   178.68173 198.72855 142.42383]
1100 Cost:  9.725016 
Prediction:
 [146.3636

1970 Cost:  7.699538 
Prediction:
 [147.07045 187.26321 178.91258 198.80623 141.86699]
1980 Cost:  7.6809235 
Prediction:
 [147.0777  187.25835 178.91493 198.80693 141.86145]
1990 Cost:  7.6624084 
Prediction:
 [147.08492 187.2535  178.91728 198.80762 141.85593]
2000 Cost:  7.6439576 
Prediction:
 [147.09213 187.24866 178.91962 198.8083  141.85043]


In [9]:
x_data = [[73., 80., 75.], [93., 88., 93.],
[89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')
# Hypothesis
hypothesis = tf.matmul(X, W) + b
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  323.79492 
Prediction:
 [[145.24286]
 [160.76596]
 [165.56267]
 [180.70366]
 [118.6845 ]]
10 Cost:  44.797123 
Prediction:
 [[159.98712]
 [178.53561]
 [183.04639]
 [199.74533]
 [132.24832]]
20 Cost:  44.558937 
Prediction:
 [[160.00641]
 [178.6068 ]
 [183.0916 ]
 [199.79689]
 [132.31265]]
30 Cost:  44.324482 
Prediction:
 [[159.98117]
 [178.62437]
 [183.08405]
 [199.79095]
 [132.33604]]
40 Cost:  44.091328 
Prediction:
 [[159.95589]
 [178.64174]
 [183.07637]
 [199.78491]
 [132.35928]]
50 Cost:  43.859394 
Prediction:
 [[159.9307 ]
 [178.65909]
 [183.06871]
 [199.77887]
 [132.38246]]
60 Cost:  43.628784 
Prediction:
 [[159.90556]
 [178.67638]
 [183.06108]
 [199.77284]
 [132.40556]]
70 Cost:  43.399345 
Prediction:
 [[159.88048]
 [178.69359]
 [183.05344]
 [199.76682]
 [132.4286 ]]
80 Cost:  43.171192 
Prediction:
 [[159.8555 ]
 [178.71082]
 [183.04587]
 [199.76085]
 [132.4516 ]]
90 Cost:  42.944214 
Prediction:
 [[159.83057]
 [178.72797]
 [183.03831]
 [199.75487]
 [132.47453]]
1

870 Cost:  28.53989 
Prediction:
 [[158.08148]
 [179.93094]
 [182.50734]
 [199.33192]
 [134.08601]]
880 Cost:  28.391895 
Prediction:
 [[158.0614 ]
 [179.94476]
 [182.50127]
 [199.32706]
 [134.10457]]
890 Cost:  28.244537 
Prediction:
 [[158.04135]
 [179.95854]
 [182.49518]
 [199.32214]
 [134.12308]]
900 Cost:  28.09805 
Prediction:
 [[158.02138]
 [179.97229]
 [182.4891 ]
 [199.31725]
 [134.14153]]
910 Cost:  27.952442 
Prediction:
 [[158.00146]
 [179.98601]
 [182.4831 ]
 [199.31244]
 [134.15994]]
920 Cost:  27.807522 
Prediction:
 [[157.9816 ]
 [179.99968]
 [182.47707]
 [199.30757]
 [134.1783 ]]
930 Cost:  27.663342 
Prediction:
 [[157.96176]
 [180.0133 ]
 [182.47104]
 [199.30273]
 [134.19661]]
940 Cost:  27.520044 
Prediction:
 [[157.94202]
 [180.0269 ]
 [182.46506]
 [199.29788]
 [134.21486]]
950 Cost:  27.377422 
Prediction:
 [[157.9223 ]
 [180.04047]
 [182.45908]
 [199.29308]
 [134.23308]]
960 Cost:  27.23566 
Prediction:
 [[157.90265]
 [180.05399]
 [182.45312]
 [199.28828]
 [134.2

1730 Cost:  18.326242 
Prediction:
 [[156.54018]
 [180.99184]
 [182.04047]
 [198.9523 ]
 [135.51363]]
1740 Cost:  18.233118 
Prediction:
 [[156.52428]
 [181.00275]
 [182.03564]
 [198.94832]
 [135.52837]]
1750 Cost:  18.140509 
Prediction:
 [[156.50845]
 [181.01367]
 [182.03087]
 [198.9444 ]
 [135.54309]]
1760 Cost:  18.048496 
Prediction:
 [[156.49266]
 [181.0245 ]
 [182.02608]
 [198.94044]
 [135.55774]]
1770 Cost:  17.956913 
Prediction:
 [[156.47694]
 [181.03537]
 [182.02133]
 [198.93654]
 [135.57239]]
1780 Cost:  17.86583 
Prediction:
 [[156.46123]
 [181.04616]
 [182.01656]
 [198.9326 ]
 [135.58696]]
1790 Cost:  17.775208 
Prediction:
 [[156.44559]
 [181.05696]
 [182.01184]
 [198.92871]
 [135.60153]]
1800 Cost:  17.68507 
Prediction:
 [[156.42996]
 [181.06772]
 [182.00713]
 [198.9248 ]
 [135.61604]]
1810 Cost:  17.59551 
Prediction:
 [[156.4144 ]
 [181.07841]
 [182.00241]
 [198.92091]
 [135.63051]]
1820 Cost:  17.506378 
Prediction:
 [[156.39886]
 [181.0891 ]
 [181.99771]
 [198.9170

In [14]:
import numpy as np
tf.set_random_seed(777) # for reproducibility
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [17]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Set up feed_dict variables inside the loop.
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict={X: x_data, Y: y_data})
#     if step % 10 == 0:
#         print(step, "Cost: ", cost_val,
#             "\nPrediction:\n", hy_val)
        
# Ask my score
print("Your score will be ", sess.run(hypothesis,
    feed_dict={X: [[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis,
    feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[179.20425]]
Other scores will be  [[175.49333]
 [179.91008]]
