In [11]:
# https://www.tensorflow.org/api_guides/python/array_ops
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [5]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])

In [9]:
print(t.ndim)
print(t.shape)
print(t[0], t[1], t[-1])
# 슬라이스, 2:5 -> 2,3,4 // 4:-1 => 4부터 마지막 전까지 4,5 
print(t[2:5], t[4:-1])

1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]


In [12]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])

pp.pprint(t)
print(t.ndim) # 차원 
print(t.shape) # 4 by 3 매트릭스

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


In [13]:
t = tf.constant([1,2,3,4]) # rank는 1, shape은 4
tf.shape(t).eval()

array([4])

In [14]:
t = tf.constant([[1,2],[3,4]]) # rank가 2
tf.shape(t).eval()

array([2, 2])

In [15]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

In [16]:
pp.pprint(t)

<tf.Tensor 'Const_2:0' shape=(1, 2, 3, 4) dtype=int32>


In [21]:
matrix1 = tf.constant([[1.,2.],[3., 4.]])
matrix2 = tf.constant([[1.],[2.]])

print("matrix1 shape: ", matrix1.shape)
print("matrix2 shape: ", matrix2.shape)

tf.matmul(matrix1, matrix2).eval()

matrix1 shape:  (2, 2)
matrix2 shape:  (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

In [22]:
(matrix1*matrix2).eval()

array([[1., 2.],
       [6., 8.]], dtype=float32)

#### Broadcasting 개념을 주의/ 유용함

    matrix1 = tf.constant([[3., 3.]])
    matrix2 = tf.constant([[2.],[2.]])
    tf.matmul(matrix1, matrix2).eval()

shape이 다르더라도 같은 shape으로 맞추어주는것이 Broadcasting

    matrix1 = tf.constant([[1., 2.]])
    matrix2 = tf.constant(3.)
    (matrix1 + matrix2).eval()

Rank가 달라도 되고

    matrix1 = tf.constant([[1., 2.]])
    matrix2 = tf.constant([3.,4.])
    (matrix1 + matrix2).eval()

Shape, Rank 둘다 달라도 됨

    matrix1 = tf.constant([[1., 2.]])
    matrix2 = tf.constant([[2.],[2.]])
    (matrix1 + matrix2).eval()

In [32]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.)
(matrix1 + matrix2).eval()

array([[4., 5.]], dtype=float32)

#### Reduce mean
평균을 구하는 데 줄여서 구한다.

축(axis)에 따라 평균을 구할수 있음.

축을 주의해야함

reduce_sum 도 유사함

축을 볼때, 일반 2차원 매트릭스에서 칼럼부분이 axis=0, 로우부분이 axis=1

In [33]:
tf.reduce_mean([1, 2], axis=0).eval()

x = [[1.,2.],[3.,4.]]
tf.reduce_mean(x). eval()

2.5

In [34]:
# 1,3의 평균, 2,4의 평균
tf.reduce_mean(x, axis=0). eval()

array([2., 3.], dtype=float32)

In [35]:
# 1,2의 평균, 3,4의 평균
tf.reduce_mean(x, axis=1). eval()

array([1.5, 3.5], dtype=float32)

#### Argmax

축별로 최대값을 찾는 것

최대값을 찾으면 해당 인덱스를 리턴하고 나머지는 0으로 채움




In [36]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

#### Reshape

가장 많이 쓰임

Reshape에서 squeeze, expand도 많이 씀


In [37]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [38]:
tf.reshape(t, shape=[-1, 3]).eval()


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
tf.reshape(t, shape=[-1, 1, 3]).eval()


array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [40]:
tf.squeeze([[0], [1], [2]]).eval()


array([0, 1, 2])

In [41]:
tf.expand_dims([0, 1, 2], 1).eval()


array([[0],
       [1],
       [2]])

#### One Hot

특정 자리만 핫하게 대게 1로 주어주는 방법

depth 만큼 사이즈를 늘리고, 차원의 깊이를 한차원 높임


In [46]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()


array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [43]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

#### casting


In [48]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()


array([1, 2, 3, 4])

#### stack

In [49]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [50]:
tf.stack([x, y, z], axis=1).eval()


array([[1, 2, 3],
       [4, 5, 6]])

#### Ones like and Zeros like


In [51]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [52]:
tf.zeros_like(x).eval()


array([[0, 0, 0],
       [0, 0, 0]])

#### Zip

In [53]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [54]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


#### Transpose

순서를 바꾸는 기능

In [55]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [56]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [57]:
t = tf.transpose(t1, [1, 0, 2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [58]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [59]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])
